import "reflect-metadata";
import { fileURLToPath } from "node:url";
import Fastify, {} from "fastify";
import cookie from "@fastify/cookie";
import cors from "@fastify/cors";
import helmet from "@fastify/helmet";
import jwt from "@fastify/jwt";
import rateLimit from "@fastify/rate-limit";
import { config } from "./config.js";
import { AppDataSource } from "./data-source.js";
import { AppError, ValidationError } from "./errors/AppError.js";
import authRoutes from "./routes/auth.js";
import vaultRoutes from "./routes/vault.js";
/**
 * Application entry point.
 *
 * Responsibilities (in order):
 *   1. Build a configured Fastify instance with all security plugins.
 *   2. Initialise the TypeORM DataSource and run pending migrations.
 *   3. Listen on the configured port.
 *
 * Exposed as a factory (`buildServer`) so tests can boot the HTTP layer
 * without binding to a port.
 */
export async function buildServer() {
    const fastify = Fastify({
        logger: {
            level: config.LOG_LEVEL,
            // Anything that could carry a session secret or a piece of
            // ciphertext is redacted before it touches a log destination.
            redact: {
                paths: [
                    "req.headers.cookie",
                    "req.headers.authorization",
                    'req.headers["set-cookie"]',
                    "res.headers['set-cookie']",
                    "req.body.auth_hash",
                    "req.body.encrypted_data",
                ],
                censor: "[REDACTED]",
            },
            ...(config.NODE_ENV === "development"
                ? { transport: { target: "pino-pretty" } }
                : {}),
        },
        requestTimeout: config.REQUEST_TIMEOUT_MS,
        // 256 KiB cap — comfortably above the 64 KiB ciphertext limit
        // (~128 KiB hex) plus JSON overhead, well below DoS territory.
        bodyLimit: 256 * 1024,
        // Off by default — flip to true only when running behind a trusted
        // reverse proxy / load balancer that sets X-Forwarded-For.
        trustProxy: false,
    });
    // ── Security plugins ────────────────────────────────────────────────────
    // helmet first so its headers (CSP, HSTS, X-Frame-Options, etc.) are
    // attached to every reply, including 4xx/5xx generated by later plugins.
    await fastify.register(helmet, {
        contentSecurityPolicy: {
            directives: {
                defaultSrc: ["'self'"],
                frameAncestors: ["'none'"],
            },
        },
        crossOriginResourcePolicy: { policy: "same-site" },
    });
    // Browsers reject credentialed requests with a wildcard origin, but we
    // pin to a single configured origin anyway to avoid any misconfiguration.
    await fastify.register(cors, {
        origin: config.FRONTEND_ORIGIN,
        credentials: true,
        methods: ["GET", "POST", "PUT", "DELETE"],
    });
    // Cookie parser must come BEFORE @fastify/jwt — the JWT plugin reads the
    // access_token cookie via request.cookies.
    await fastify.register(cookie);
    await fastify.register(jwt, {
        secret: config.JWT_SECRET,
        cookie: {
            cookieName: "access_token",
            signed: false,
        },
    });
    // Default per-IP rate limit. Auth routes apply stricter per-route caps
    // via `config.rateLimit` on their registrations. In-memory store is
    // fine for single-instance; swap to the redis store before horizontal
    // scaling to keep limits coherent across replicas.
    await fastify.register(rateLimit, {
        max: 100,
        timeWindow: "1 minute",
    });
    // ── Decorators ──────────────────────────────────────────────────────────
    /**
     * onRequest hook used by vault routes. Verifies the access_token JWT
     * from the cookie. On failure we return a generic 401 — the JWT
     * library's error messages distinguish "missing" / "expired" / "invalid"
     * which would otherwise be a small but real information leak.
     */
    fastify.decorate("authenticate", async function (request, reply) {
        try {
            await request.jwtVerify();
        }
        catch {
            reply.code(401).send({ error: "Unauthorized" });
        }
    });
    // ── Routes ──────────────────────────────────────────────────────────────
    await fastify.register(authRoutes);
    await fastify.register(vaultRoutes);
    fastify.get("/health", { logLevel: "warn" }, async () => ({ status: "ok" }));
    // ── Global error handler ────────────────────────────────────────────────
    /**
     * Translates everything thrown by services / plugins into a JSON reply.
     *
     * Policy:
     *   - Domain `AppError` with `expose: true`  → reply.status(code).send({ error: message })
     *   - Domain `AppError` with `expose: false` → reply 5xx with generic message
     *   - Fastify-native 4xx (validation, etc.)  → pass status + message through
     *   - Anything else                          → 500 generic, full error logged
     *
     * Stack traces and internal error specifics never reach the client.
     */
    fastify.setErrorHandler((error, request, reply) => {
        if (error instanceof AppError) {
            const body = {
                error: error.expose ? error.message : "Internal server error",
            };
            if (error instanceof ValidationError && error.details !== undefined) {
                body.details = error.details;
            }
            reply.status(error.statusCode).send(body);
            return;
        }
        // Fastify v5 types the error as `unknown` — narrow before reading fields.
        const errWithStatus = error;
        const statusCode = errWithStatus.statusCode;
        if (typeof statusCode === "number" && statusCode >= 400 && statusCode < 500) {
            // Fastify validation errors / rate-limit 429s carry safe messages.
            const safeMessage = typeof errWithStatus.message === "string" ? errWithStatus.message : "Bad request";
            reply.status(statusCode).send({ error: safeMessage });
            return;
        }
        request.log.error({ err: error }, "Unhandled error");
        reply.status(500).send({ error: "Internal server error" });
    });
    return fastify;
}
/**
 * Boot sequence: open the DB pool, run any pending migrations, then start
 * Fastify. Migrations run explicitly (not via `migrationsRun: true` on the
 * data source) so a failure surfaces here, with a clear log line, instead
 * of on the first SQL query.
 */
async function start() {
    await AppDataSource.initialize();
    const hasPending = await AppDataSource.showMigrations();
    if (hasPending) {
        await AppDataSource.runMigrations();
    }
    const server = await buildServer();
    try {
        await server.listen({ host: "0.0.0.0", port: config.PORT });
    }
    catch (err) {
        server.log.error({ err }, "Server failed to start");
        await AppDataSource.destroy().catch(() => undefined);
        process.exit(1);
    }
}
// Auto-start only when this file is the process entry — keeps the module
// importable from tests without booting the server.
const isEntryPoint = process.argv[1] === fileURLToPath(import.meta.url);
if (isEntryPoint) {
    start().catch((err) => {
        // No fastify logger yet — fall back to stderr.
        console.error("Fatal startup error:", err);
        process.exit(1);
    });
}
//# sourceMappingURL=index.js.map